# Generated by Django 3.2 on 2021-04-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('contributor', models.CharField(max_length=200)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
